### PR TITLE
Admin/manage fees/show registered fees

### PR DESCRIPTION
**Pull request by tsato21**
【admin/manageFees/showRegisteredFees】Update style and route
*This includes some additions and updates that were commit and pushed previously.

- Added showFees function in FeesController
- Create show.blade.php for Fees
- Updated style.css: divided into categories such as main and modal (consulted in our members)
- Used @yield in admin.blade.php to dynamically change the tab name
- Added the route for showFees function and modified the route code for showUsers for Admin for the sake of consistency of url and name (removed "/showusers")

### CODE REVIEW

**Review by KobeSergio — APPROVED** [review]

**Comment by KobeSergio** [comment]
Please resolve conflicts first @tsato21 so we can merge to main :)

**Comment by tsato21** [comment]
@KobeSergio 
I have resoved the confilicts and committed and pushed again.
Can you kindly check the udpates and merge this into the main?

**Comment by KobeSergio** [comment]
@tsato21 sorry, there has been another conflict upon merging previous PRs 😆. Kindly resolve them again thank you :)

**Comment by tsato21** [comment]
@KobeSergio
I have resoved the confilicts and committed and pushed again.
Can you kindly check the udpates and merge this into the main?

**Pull request merged**
